### ISSUE TITLE
What's the purpose of the removeListener and removeAllListeners calls?

### ISSUE THREAD

**Issue by pors** [mbenford/ngSocketIO#3]
What's exactly the purpose of the removeListener and removeAllListeners calls? 

Could you please explain, or even better, create a relevant example? Is it needed when the connected is lost? If you don't call the mentioned methods, what will happen?

I don't see any need for it in my own code as the number of listeners doesn't grow after disconnect, but for some people that does happen apparently, see e.g. http://stackoverflow.com/questions/14389049/how-to-use-angularjs-with-socket-io.

Would be great to see an example where the use of  removeListener or removeAllListeners is required.

**Comment by mbenford** [comment]
Hi Mark.

Both methods belong to SocketIO's [client implementation](https://github.com/LearnBoost/socket.io-client/blob/master/socket.io.js) and ngSocketIO simply makes them available to Angular apps.

They have no documentation whatsoever (or at least I couldn't find it anywhere), but their implementation is pretty straightforward:

``` javascript
Emitter.prototype.off =
Emitter.prototype.removeListener =
Emitter.prototype.removeAllListeners = function(event, fn){
  this._callbacks = this._callbacks || {};

  // all
  if (0 == arguments.length) {
    this._callbacks = {};
    return this;
  }

  // specific event
  var callbacks = this._callbacks[event];
  if (!callbacks) return this;

  // remove all handlers
  if (1 == arguments.length) {
    delete this._callbacks[event];
    return this;
  }

  // remove specific handler
  var i = index(callbacks, fn._off || fn);
  if (~i) callbacks.splice(i, 1);
  return this;
};
```

Basically they remove either one or all event handlers of a given event, which means those handlers won't get executed when that event is triggered. I'd say you should use them whenever you're no longer interested in processing an event. In Angular apps, a good moment to do that is when a scope is destroyed (as said in the answer for the question you have posted), since that would mean that the state of the application has changed and any event handlers registered for that scope might be irrelevant at this point. 

Take for instance a chat app with two views: one for the user to enter its name and another one for him/her to send and read messages. Let's call the former `LoginView` and the latter `ChatView`. In `ChatView` you subscribe for a `message` event so every time a new message arrives the app can print it on screen. When the user leaves the  `ChatView` and returns to the `LoginView` you should remove that event handler, otherwise it will continue to get executed as messages arrive, even though the app isn't interested in that anymore.

Hope this helps.

Kind regards.

**Comment by pors** [comment]
Cool, that example makes it perfectly clear now. Thanks!
